'use client';

import Link from 'next/link';
import { useState } from 'react';

export default function LoginPage() {
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [message, setMessage] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const endpoint = mode === 'login' ? '/api/auth/login' : '/api/auth/register'; const body = mode === 'login' ? { email: form.get('email'), password: form.get('password') } : { name: form.get('name'), email: form.get('email'), password: form.get('password') }; const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:5000'}${endpoint}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (response.ok) { localStorage.setItem('accessToken', data.accessToken); window.location.href = mode === 'register' ? '/profile' : '/'; } else setMessage(data.error ?? 'Unable to continue'); }
  return <main className="site-shell"><div className="container"><header className="header"><Link href="/" className="brand"><span className="brand-mark">✦</span>videxpulse<span style={{ color: 'var(--brand)' }}>.</span></Link></header><section className="section" style={{ maxWidth: 460, margin: '50px auto' }}><div className="eyebrow">Your marketplace account</div><h1 style={{ fontFamily: 'Plus Jakarta Sans', fontSize: '2.5rem', letterSpacing: '-.06em' }}>{mode === 'login' ? 'Sign in' : 'Create account'}</h1><div style={{ display: 'flex', gap: 8, margin: '22px 0' }}><button type="button" className={`button ${mode === 'login' ? 'button-primary' : 'button-light'}`} onClick={() => setMode('login')}>Sign in</button><button type="button" className={`button ${mode === 'register' ? 'button-primary' : 'button-light'}`} onClick={() => setMode('register')}>Sign up</button></div><form onSubmit={submit} style={{ display: 'grid', gap: 15 }}>{mode === 'register' && <input className="search-input" name="name" required placeholder="Full name" style={{ border: '1px solid var(--line)', borderRadius: 12 }} />}<input className="search-input" name="email" type="email" required placeholder="Email address" style={{ border: '1px solid var(--line)', borderRadius: 12 }} /><input className="search-input" name="password" type="password" minLength={8} required placeholder="Password (minimum 8 characters)" style={{ border: '1px solid var(--line)', borderRadius: 12 }} /><button className="button button-primary" type="submit">{mode === 'login' ? 'Sign in' : 'Create account'}</button>{message && <p style={{ color: 'var(--brand-dark)' }}>{message}</p>}</form></section></div></main>;
}
