'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:5000';
export default function AccountMenu() {
  const [user, setUser] = useState<any>(null); const [open, setOpen] = useState(false);
  useEffect(() => { const token = localStorage.getItem('accessToken'); fetch(`${API}/api/profile`, { credentials: 'include', headers: token ? { authorization: `Bearer ${token}` } : {} }).then((r) => r.ok ? r.json() : null).then((d) => setUser(d?.profile ?? null)).catch(() => setUser(null)); }, []);
  async function logout() { await fetch(`${API}/api/auth/logout`, { method: 'POST', credentials: 'include' }); localStorage.removeItem('accessToken'); window.location.href = '/'; }
  if (!user) return <nav className="nav"><Link href="/search">Browse ads</Link><Link href="/login">Sign in</Link><Link href="/login?mode=register" className="button button-light">Sign up</Link><Link href="/post" className="button button-primary">Post an ad&nbsp; ＋</Link></nav>;
  const initials = (user.firstName || user.name || user.email || 'U').slice(0, 1).toUpperCase();
  return <nav className="nav" style={{ alignItems: 'center' }}><Link href="/search">Browse ads</Link><Link href="/post" className="button button-primary">Post an ad&nbsp; ＋</Link><div style={{ position: 'relative' }}><button type="button" className="button button-light" onClick={() => setOpen(!open)} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>{user.avatarUrl ? <img src={user.avatarUrl} alt="" style={{ width: 28, height: 28, borderRadius: '50%', objectFit: 'cover' }} /> : <span className="brand-mark" style={{ width: 28, height: 28, fontSize: '.85rem' }}>{initials}</span>}<span>{user.firstName || user.name || 'Account'}</span><span>⌄</span></button>{open && <div style={{ position: 'absolute', right: 0, top: 'calc(100% + 8px)', zIndex: 10, minWidth: 180, padding: 8, background: 'white', border: '1px solid var(--line)', borderRadius: 14, boxShadow: '0 12px 30px rgba(20,30,45,.12)' }}><Link href="/profile" className="button button-light" style={{ display: 'block', width: '100%', marginBottom: 6 }}>My profile</Link>{user.role === 'ADMIN' && <Link href="/admin" className="button button-light" style={{ display: 'block', width: '100%', marginBottom: 6 }}>Admin console</Link>}<button type="button" onClick={logout} className="button button-light" style={{ width: '100%' }}>Log out</button></div>}</div></nav>;
}
